# Changes here will be overwritten by Copier
AddCopierCI: false
AnswerStrategy: recommended-ask
Authors: Till Prölß, René Skukies, Benedikt Ehinger
CheckExplicitImports: false
CodeOfConductContact: Benedikt Ehinger
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Till Prölß, René Skukies, Benedikt Ehinger
MarkdownIndentation: 2
PackageName: UnfoldRIDE
PackageOwner: unfoldtoolbox
PackageUUID: 348b5554-d1f6-52bd-94b1-729601d351bf
RunJuliaNightlyOnCI: false
UseCirrusCI: false
_commit: v0.14.1
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
